modbus:
  ip: "192.168.1.1"
  port: 502
  slave_id: 100
  battery_register: 843
  register_type: "input"
  input_register: 829
  not_connected_input_value: 240

threshold: 20
poll_interval: 5
alert_threshold: 85


log_file: "modbus-shutdown.log"

email:
  smtp_server: "smtp-relay.brevo.com"
  smtp_port: 587
  username: "your@email.com"
  password: "your-smtp-password"
  from: "your@email.com"
  to: "admin@example.com"
  subject: "CRITICAL: UPS Battery Low - Shutdown Initiated"
